CREATE DATABASE mola DEFAULT CHARACTER SET 'utf8'
  DEFAULT COLLATE 'utf8_unicode_ci';

USE mola;

#DROP TABLE UserPrincipal;
CREATE TABLE UserPrincipal (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(30) NOT NULL,
  HashedPassword BINARY(60) NOT NULL,
  UNIQUE KEY UserPrincipal_Username (Username)
) ENGINE = InnoDB;

#DROP TABLE Following;
CREATE TABLE Following (
  FollowerId BIGINT UNSIGNED NOT NULL,
  FolloweeId BIGINT UNSIGNED NOT NULL,
  CONSTRAINT Following_fk_FollowerId
    FOREIGN KEY (FollowerId)
    REFERENCES UserPrincipal (Id)
    ON DELETE CASCADE,
  CONSTRAINT Following_fk_FolloweeId
    FOREIGN KEY (FolloweeId)
    REFERENCES UserPrincipal (Id)
    ON DELETE CASCADE,
  PRIMARY KEY (FollowerId, FolloweeId)
) ENGINE = InnoDB;

#DROP TABLE UserProfile;
CREATE TABLE UserProfile (
  UserId BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  Title VARCHAR(35) NULL, 
  FirstName VARCHAR(35) NOT NULL,
  LastName VARCHAR(35) NOT NULL,
  NameSuffix VARCHAR(35) NULL,
  DisplayName VARCHAR(70) NULL,
  Gender ENUM('MALE', 'FEMALE', 'UNSPECIFIED') NULL,
  Birthday DATE NULL,
  CONSTRAINT UserProfile_fk_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

#DROP TABLE Address;
CREATE TABLE Address (
  UserId BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  Name VARCHAR(35) NULL,
  BuildingNumber VARCHAR(35) NULL,
  Street VARCHAR(35) NULL,
  Town VARCHAR(35) NULL,
  State VARCHAR(35) NULL,
  Country VARCHAR(70) NOT NULL,
  CONSTRAINT Address_fk_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

#DROP TABLE Course;
CREATE TABLE Course (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  AuthorId BIGINT UNSIGNED NOT NULL,
  Title VARCHAR(70) NOT NULL,
  Topic VARCHAR(35) NULL,
  Degree ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL,
  Description VARCHAR(255) NULL,
  CreateDate DATETIME NOT NULL,
  PublishDate DATETIME NULL,
  State ENUM('DRAFT', 'OPENED', 'CLOSED', 'BANNED') NULL,
  CONSTRAINT Course_fk_AuthorId FOREIGN KEY (AuthorId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE
) ENGINE = InnoDB;