DROP DATABASE mola;

CREATE DATABASE mola DEFAULT CHARACTER SET 'utf8'
  DEFAULT COLLATE 'utf8_unicode_ci';

USE mola;

#DROP TABLE UserPrincipal;
CREATE TABLE UserPrincipal (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(30) NOT NULL,
  HashedPassword BINARY(60) NOT NULL,
  #Profile  
  Title VARCHAR(35) NULL, 
  FirstName VARCHAR(35) NOT NULL,
  LastName VARCHAR(35) NOT NULL,
  NameSuffix VARCHAR(35) NULL,
  DisplayName VARCHAR(70) NULL,
  Gender ENUM('MALE', 'FEMALE', 'UNSPECIFIED') NULL,
  Birthday DATE NULL,
  
  UNIQUE KEY UserPrincipal_Username (Username)
) ENGINE = InnoDB;

#DROP TABLE Following;
CREATE TABLE Following (
  FollowerId BIGINT UNSIGNED NOT NULL,
  FolloweeId BIGINT UNSIGNED NOT NULL,
  
  CONSTRAINT Following_fk_FollowerId FOREIGN KEY (FollowerId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE,
  CONSTRAINT Following_fk_FolloweeId FOREIGN KEY (FolloweeId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE,
  PRIMARY KEY (FollowerId, FolloweeId)
) ENGINE = InnoDB;

CREATE TABLE Language (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  EnglishName VARCHAR(80) NOT NULL,
  NativeName VARCHAR(80) NOT NULL,
  
  UNIQUE KEY Language_EnglishName (EnglishName),
  UNIQUE KEY Language_NativeName (NativeName)
) ENGINE = InnoDB;

CREATE TABLE UsedLanguage (
  UserId BIGINT UNSIGNED NOT NULL,
  LanguageId BIGINT UNSIGNED NOT NULL,
  UseFor ENUM('LEARNING', 'TEACHING') NOT NULL,
  
  PRIMARY KEY (UserId, LanguageId),
  CONSTRAINT UsedLanguage_fk_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal(Id) ON DELETE CASCADE,
  CONSTRAINT UsedLanguage_fk_LanguageId FOREIGN KEY (LanguageId)
    REFERENCES Language(Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Role(
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Title VARCHAR(35),
  
  UNIQUE KEY Role_Title (Title)
) ENGINE = InnoDB;

CREATE TABLE UserInRole (
  UserId BIGINT UNSIGNED NOT NULL,
  RoleId BIGINT UNSIGNED NOT NULL,
  
  PRIMARY KEY (UserId, RoleId),
  CONSTRAINT UserInRole_fk_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal(Id) ON DELETE CASCADE,
  CONSTRAINT UserInRole_fk_RoleId FOREIGN KEY (RoleId)
    REFERENCES Role(Id) ON DELETE CASCADE
) ENGINE = InnoDB;

#DROP TABLE Address;
CREATE TABLE Address (
  UserId BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  Name VARCHAR(35) NULL,
  BuildingNumber VARCHAR(35) NULL,
  Street VARCHAR(35) NULL,
  Town VARCHAR(35) NULL,
  State VARCHAR(35) NULL,
  Country VARCHAR(70) NOT NULL,
  
  CONSTRAINT Address_fk_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

#DROP TABLE Course;
CREATE TABLE Course (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  AuthorId BIGINT UNSIGNED NOT NULL,
  LanguageId BIGINT UNSIGNED NOT NULL,
  Title VARCHAR(70) NOT NULL,
  Topic VARCHAR(35) NULL,
  Degree ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL,
  Description VARCHAR(255) NULL,
  CreateDate DATETIME NOT NULL,
  State ENUM('DRAFT', 'OPENED', 'CLOSED', 'BANNED') NULL,
  
  CONSTRAINT Course_fk_AuthorId FOREIGN KEY (AuthorId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE,
  CONSTRAINT Course_fk_LanguageId FOREIGN KEY (LanguageId)
    REFERENCES Language (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Chapter (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CourseId BIGINT UNSIGNED NOT NULL,
  Title VARCHAR(70) NOT NULL,
  Description VARCHAR(255) NULL,
  
  CONSTRAINT Chapter_fk_CourseId FOREIGN KEY (CourseId)
    REFERENCES Course (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Lesson (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ChapterId BIGINT UNSIGNED NOT NULL,
  Title VARCHAR(70) NOT NULL,
  Description VARCHAR(255) NULL,
  Duration INT NULL,
  
  CONSTRAINT Lesson_fk_ChapterId FOREIGN KEY (ChapterId)
    REFERENCES Chapter (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Enroll (
  UserId BIGINT UNSIGNED NOT NULL,
  CourseId BIGINT UNSIGNED NOT NULL,
  EnrollDate DATETIME NOT NULL,
  Grade INT NULL,
  
  PRIMARY KEY (UserId, CourseId),
  CONSTRAINT Enroll_fk_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE,
  CONSTRAINT Enroll_fk_CourseId FOREIGN KEY (CourseId)
    REFERENCES Course (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Rank (
  UserId BIGINT UNSIGNED NOT NULL,
  CourseId BIGINT UNSIGNED NOT NULL,
  LessonId BIGINT UNSIGNED NULL,
  Score INT NULL,
  
  UNIQUE KEY (UserId, CourseId, LessonId),
  CONSTRAINT Rank_fk_UserId FOREIGN KEY (UserId)
    REFERENCES Enroll (UserId) ON DELETE CASCADE,
  CONSTRAINT Rank_fk_CourseId FOREIGN KEY (CourseId)
    REFERENCES Enroll (CourseId) ON DELETE CASCADE,
  CONSTRAINT Rank_fk_LessonId FOREIGN KEY (LessonId)
    REFERENCES Lesson (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Agenda (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DailyAgenda BIT NULL,
  WeeklyAgenda INT NULL
) ENGINE = InnoDB;

CREATE TABLE TimeFrame (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  UserId BIGINT UNSIGNED NOT NULL,
  AgendaId BIGINT UNSIGNED NOT NULL,
  StartDate DATETIME NOT NULL,
  EndDate DATETIME NOT NULL,
  
  CONSTRAINT TimeFrame_fk_UserId FOREIGN KEY (UserId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE,
  CONSTRAINT TimeFrame_fk_AgendaId FOREIGN KEY (AgendaId)
    REFERENCES Agenda (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Slot (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TimeFrameId BIGINT UNSIGNED NOT NULL,
  FromTime TIME NOT NULL,
  ToTime TIME NOT NULL,
  
  CONSTRAINT Slot_fk_TimeFrameId FOREIGN KEY (TimeFrameId)
    REFERENCES TimeFrame (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Meeting (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LearnerId BIGINT UNSIGNED NOT NULL,
  TeacherId BIGINT UNSIGNED NOT NULL,
  CourseId BIGINT UNSIGNED NOT NULL,
  LessonId BIGINT UNSIGNED NULL,
  MeetingDate DATETIME NOT NULL,
  
  TeacherLoginTime TIME NULL,
  TeacherLogoutTime TIME NULL,
  LearnerLoginTime TIME NULL,
  LearnerLogoutTime TIME NULL,
  
  CONSTRAINT Meeting_fk_LearnerId FOREIGN KEY (LearnerId)
    REFERENCES Enroll (UserId) ON DELETE CASCADE,
  CONSTRAINT Meeting_fk_TeacherId FOREIGN KEY (TeacherId)
    REFERENCES UserPrincipal (Id) ON DELETE CASCADE,
  CONSTRAINT Meeting_fk_CourseId FOREIGN KEY (CourseId)
    REFERENCES Enroll (CourseId) ON DELETE CASCADE,
  CONSTRAINT Meeting_fk_LessonId FOREIGN KEY (LessonId)
    REFERENCES Lesson (Id) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE Register (
  SlotId BIGINT UNSIGNED NOT NULL,
  MeetingId BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (SlotId, MeetingId),
  CONSTRAINT Register_fk_SlotId FOREIGN KEY (SlotId)
    REFERENCES Slot (Id) ON DELETE CASCADE,
  CONSTRAINT Register_fk_MeetingId FOREIGN KEY (MeetingId)
    REFERENCES Meeting (Id) ON DELETE CASCADE
) ENGINE = InnoDB;