USE mola;

INSERT INTO Role (Id, Title) VALUES (1, 'Teacher');
INSERT INTO Role (Id, Title) VALUES (2, 'Learner');

INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(1,'Afar', 'Afar');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(2,'Abkhazian', 'Аҧсуа');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(3,'Afrikaans', 'Afrikaans');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(4,'Akan', 'Akana');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(5,'Alemannic', 'Alemannisch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(6,'Amharic', 'አማርኛ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(7,'Aragonese', 'Aragonés');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(8,'Anglo-Saxon / Old English', 'Englisc');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(9,'Arabic', 'العربية');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(10,'Aramaic', 'ܣܘܪܬ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(11,'Assamese', 'অসমীয়া');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(12,'Asturian', 'Asturianu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(13,'Avar', 'Авар');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(14,'Aymara', 'Aymar');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(15,'Azerbaijani', 'Azərbaycanca / آذربايجان');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(16,'Bashkir', 'Башҡорт');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(17,'Bavarian', 'Boarisch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(18,'Samogitian', 'Žemaitėška');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(19,'Bikol', 'Bikol Central');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(20,'Belarusian', 'Беларуская');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(21,'Belarusian (Taraškievica)', 'Беларуская (тарашкевіца)');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(22,'Bulgarian', 'Български');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(23,'Bihari', 'भोजपुरी');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(24,'Bislama', 'Bislama');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(25,'Bambara', 'Bamanankan');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(26,'Bengali', 'বাংলা');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(27,'Tibetan', 'བོད་ཡིག / Bod skad');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(28,'Bishnupriya Manipuri', 'ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(29,'Breton', 'Brezhoneg');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(30,'Bosnian', 'Bosanski');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(31,'Buginese', 'ᨅᨔ ᨕᨘᨁᨗ / Basa Ugi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(32,'Buriat (Russia)', 'Буряад хэлэн');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(33,'Catalan', 'Català');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(34,'Min Dong Chinese', 'Mìng-dĕ̤ng-ngṳ̄ / 閩東語');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(35,'Chechen', 'Нохчийн');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(36,'Cebuano', 'Sinugboanong Binisaya');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(37,'Chamorro', 'Chamoru');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(38,'Choctaw', 'Choctaw');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(39,'Cherokee', 'ᏣᎳᎩ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(40,'Cheyenne', 'Tsetsêhestâhese');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(41,'Corsican', 'Corsu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(42,'Cree', 'Nehiyaw');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(43,'Czech', 'Česky');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(44,'Kashubian', 'Kaszëbsczi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(45,'Old Church Slavonic / Old Bulgarian', 'словѣньскъ / slověnĭskŭ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(46,'Chuvash', 'Чăваш');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(47,'Welsh', 'Cymraeg');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(48,'Danish', 'Dansk');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(49,'German', 'Deutsch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(50,'Dimli', 'Zazaki');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(51,'Lower Sorbian', 'Dolnoserbski');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(52,'Divehi', 'ދިވެހިބަސް');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(53,'Dzongkha', 'ཇོང་ཁ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(54,'Ewe', 'Ɛʋɛ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(55,'Farsi', 'فارسی');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(56,'Greek', 'Ελληνικά');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(57,'English', 'English');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(58,'Esperanto', 'Esperanto');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(59,'Spanish', 'Español');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(60,'Estonian', 'Eesti');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(61,'Basque', 'Euskara');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(62,'Extremaduran', 'Estremeñu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(63,'Peul', 'Fulfulde');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(64,'Finnish', 'Suomi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(65,'Võro', 'Võro');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(66,'Fijian', 'Na Vosa Vakaviti');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(67,'Faroese', 'Føroyskt');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(68,'French', 'Français');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(69,'Arpitan / Franco-Provençal', 'Arpitan / francoprovençal');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(70,'Friulian', 'Furlan');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(71,'West Frisian', 'Frysk');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(72,'Irish', 'Gaeilge');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(73,'Gan Chinese', '贛語');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(74,'Scottish Gaelic', 'Gàidhlig');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(75,'Gilbertese', 'Taetae ni kiribati');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(76,'Galician', 'Galego');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(77,'Guarani', "Avañe'ẽ");
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(78,'Gothic', 'gutisk');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(79,'Gujarati', 'ગુજરાતી');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(80,'Manx', 'Gaelg');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(81,'Hausa', 'هَوُسَ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(82,'Hakka Chinese', '客家語/Hak-kâ-ngî');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(83,'Hawaiian', 'Hawai`i');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(84,'Hebrew', 'עברית');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(85,'Hindi', 'हिन्दी');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(86,'Hiri Motu', 'Hiri Motu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(87,'Croatian', 'Hrvatski');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(88,'Haitian', 'Krèyol ayisyen');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(89,'Hungarian', 'Magyar');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(90,'Armenian', 'Հայերեն');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(91,'Herero', 'Otsiherero');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(92,'Interlingua', 'Interlingua');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(93,'Indonesian', 'Bahasa Indonesia');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(94,'Interlingue', 'Interlingue');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(95,'Igbo', 'Igbo');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(96,'Sichuan Yi', 'ꆇꉙ / 四川彝语');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(97,'Inupiak', 'Iñupiak');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(98,'Ilokano', 'Ilokano');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(99,'Ido', 'Ido');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(100,'Icelandic', 'Íslenska');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(101,'Italian', 'Italiano');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(102,'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(103,'Japanese', '日本語');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(104,'Lojban', 'Lojban');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(105,'Javanese', 'Basa Jawa');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(106,'Georgian', 'ქართული');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(107,'Kongo', 'KiKongo');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(108,'Kikuyu', 'Gĩkũyũ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(109,'Kuanyama', 'Kuanyama');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(110,'Kazakh', 'Қазақша');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(111,'Greenlandic', 'Kalaallisut');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(112,'Cambodian', 'ភាសាខ្មែរ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(113,'Kannada', 'ಕನ್ನಡ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(114,'Khowar', 'کھوار');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(115,'Korean', '한국어');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(116,'Kanuri', 'Kanuri');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(117,'Kashmiri', 'कश्मीरी / كشميري');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(118,'Ripuarian', 'Ripoarisch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(119,'Kurdish', 'Kurdî / كوردی');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(120,'Komi', 'Коми');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(121,'Cornish', 'Kernewek');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(122,'Kirghiz', 'Kırgızca / Кыргызча');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(123,'Latin', 'Latina');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(124,'Ladino / Judeo-Spanish', 'Dzhudezmo / Djudeo-Espanyol');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(125,'Lango', 'Leb Lango / Luo');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(126,'Luxembourgish', 'Lëtzebuergesch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(127,'Ganda', 'Luganda');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(128,'Limburgian', 'Limburgs');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(129,'Ligurian', 'Líguru');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(130,'Lombard', 'Lumbaart');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(131,'Lingala', 'Lingála');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(132,'Laotian', 'ລາວ / Pha xa lao');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(133,'Lithuanian', 'Lietuvių');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(134,'Latvian', 'Latviešu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(135,'Banyumasan', 'Basa Banyumasan');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(136,'Malagasy', 'Malagasy');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(137,'Mandarin', '官話/官话');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(138,'Marshallese', 'Kajin Majel / Ebon');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(139,'Maori', 'Māori');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(140,'Minangkabau', 'Minangkabau');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(141,'Macedonian', 'Македонски');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(142,'Malayalam', 'മലയാളം');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(143,'Mongolian', 'Монгол');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(144,'Moldovan', 'Moldovenească');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(145,'Marathi', 'मराठी');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(146,'Malay', 'Bahasa Melayu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(147,'Maltese', 'bil-Malti');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(148,'Creek / Muskogee', 'Mvskoke');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(149,'Burmese', 'Myanmasa');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(150,'Nauruan', 'Dorerin Naoero');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(151,'Nahuatl', 'Nahuatl');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(152,'Neapolitan', 'Nnapulitano');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(153,'North Ndebele', 'Sindebele');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(154,'Low German / Low Saxon', 'Plattdüütsch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(155,'Dutch Low Saxon', 'Nedersaksisch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(156,'Nepali', 'नेपाली');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(157,'Newar', 'नेपालभाषा / Newah Bhaye');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(158,'Ndonga', 'Oshiwambo');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(159,'Dutch', 'Nederlands');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(160,'Norwegian Nynorsk', 'Norsk (nynorsk)');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(161,'Norwegian', 'Norsk (bokmål / riksmål)');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(162,'South Ndebele', 'isiNdebele');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(163,'Northern Sotho', 'Sesotho sa Leboa / Sepedi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(164,'Norman', 'Nouormand / Normaund');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(165,'Navajo', 'Diné bizaad');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(166,'Chichewa', 'Chi-Chewa');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(167,'Occitan', 'Occitan');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(168,'Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(169,'Oromo', 'Oromoo');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(170,'Oriya', 'ଓଡ଼ିଆ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(171,'Ossetian / Ossetic', 'Иронау');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(172,'Panjabi / Punjabi', 'ਪੰਜਾਬੀ / पंजाबी / پنجابي');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(173,'Pangasinan', 'Pangasinan');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(174,'Kapampangan', 'Kapampangan');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(175,'Papiamentu', 'Papiamentu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(176,'Pennsylvania German', 'Deitsch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(177,'Pali', 'Pāli / पाऴि');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(178,'Norfolk', 'Norfuk');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(179,'Polish', 'Polski');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(180,'Piedmontese', 'Piemontèis');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(181,'Pashto', 'پښتو');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(182,'Portuguese', 'Português');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(183,'Quechua', 'Runa Simi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(184,'Raeto Romance', 'Rumantsch');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(185,'Romani', 'Romani / रोमानी');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(186,'Kirundi', 'Kirundi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(187,'Romanian', 'Română');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(188,'Aromanian', 'Armâneashti');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(189,'Russian', 'Русский');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(190,'Rwandi', 'Kinyarwandi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(191,'Sanskrit', 'संस्कृतम्');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(192,'Sardinian', 'Sardu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(193,'Sicilian', 'Sicilianu');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(194,'Scots', 'Scots');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(195,'Sindhi', 'सिनधि');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(196,'Northern Sami', 'Davvisámegiella');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(197,'Sango', 'Sängö');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(198,'Serbo-Croatian', 'Srpskohrvatski / Српскохрватски');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(199,'Sinhalese', 'සිංහල');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(200,'Simple English', 'Simple English');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(201,'Slovak', 'Slovenčina');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(202,'Slovenian', 'Slovenščina');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(203,'Samoan', 'Gagana Samoa');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(204,'Shona', 'chiShona');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(205,'Somalia', 'Soomaaliga');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(206,'Albanian', 'Shqip');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(207,'Serbian', 'Српски');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(208,'Swati', 'SiSwati');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(209,'Southern Sotho', 'Sesotho');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(210,'Sundanese', 'Basa Sunda');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(211,'Swedish', 'Svenska');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(212,'Swahili', 'Kiswahili');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(213,'Tamil', 'தமிழ்');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(214,'Telugu', 'తెలుగు');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(215,'Tetum', 'Tetun');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(216,'Tajik', 'Тоҷикӣ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(217,'Thai', 'ไทย / Phasa Thai');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(218,'Tigrinya', 'ትግርኛ');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(219,'Turkmen', 'Туркмен / تركمن');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(220,'Tagalog', 'Tagalog');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(221,'Klingon', 'tlhIngan-Hol');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(222,'Tswana', 'Setswana');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(223,'Tonga', 'Lea Faka-Tonga');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(224,'Tok Pisin', 'Tok Pisin');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(225,'Turkish', 'Türkçe');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(226,'Tsonga', 'Xitsonga');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(227,'Tatar', 'Tatarça');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(228,'Tumbuka', 'chiTumbuka');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(229,'Twi', 'Twi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(230,'Tahitian', 'Reo Mā`ohi');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(231,'Udmurt', 'Удмурт кыл');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(232,'Uyghur', 'Uyƣurqə / ئۇيغۇرچە');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(233,'Ukrainian', 'Українська');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(234,'Urdu', 'اردو');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(235,'Uzbek', 'Ўзбек');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(236,'Venda', 'Tshivenḓa');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(237,'Vietnamese', 'Tiếng Việt');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(238,'Venetian', 'Vèneto');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(239,'West Flemish', 'West-Vlaoms');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(240,'Volapük', 'Volapük');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(241,'Walloon', 'Walon');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(242,'Waray / Samar-Leyte Visayan', 'Winaray / Binisaya Lineyte-Samarnon');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(243,'Wolof', 'Wollof');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(244,'Kalmyk', 'Хальмг');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(245,'Xhosa', 'isiXhosa');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(246,'Yiddish', 'ייִדיש');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(247,'Yoruba', 'Yorùbá');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(248,'Zhuang', 'Cuengh / Tôô / 壮语');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(249,'Chinese', '中文');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(250,'Classical Chinese', '文言');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(251,'Minnan', 'Bân-lâm-gú');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(252,'Cantonese', '粵語 / 粤语');
INSERT INTO Language (Id, EnglishName, NativeName)   VALUES(253,'Zulu', 'isiZulu');
