USE mola;

INSERT INTO Language (EnglishName, NativeName)   VALUES('Afar', 'Afar');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Abkhazian', 'Аҧсуа');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Afrikaans', 'Afrikaans');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Akan', 'Akana');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Alemannic', 'Alemannisch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Amharic', 'አማርኛ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Aragonese', 'Aragonés');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Anglo-Saxon / Old English', 'Englisc');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Arabic', 'العربية');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Aramaic', 'ܣܘܪܬ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Assamese', 'অসমীয়া');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Asturian', 'Asturianu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Avar', 'Авар');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Aymara', 'Aymar');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Azerbaijani', 'Azərbaycanca / آذربايجان');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bashkir', 'Башҡорт');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bavarian', 'Boarisch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Samogitian', 'Žemaitėška');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bikol', 'Bikol Central');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Belarusian', 'Беларуская');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Belarusian (Taraškievica)', 'Беларуская (тарашкевіца)');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bulgarian', 'Български');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bihari', 'भोजपुरी');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bislama', 'Bislama');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bambara', 'Bamanankan');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bengali', 'বাংলা');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tibetan', 'བོད་ཡིག / Bod skad');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bishnupriya Manipuri', 'ইমার ঠার/বিষ্ণুপ্রিয়া মণিপুরী');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Breton', 'Brezhoneg');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Bosnian', 'Bosanski');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Buginese', 'ᨅᨔ ᨕᨘᨁᨗ / Basa Ugi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Buriat (Russia)', 'Буряад хэлэн');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Catalan', 'Català');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Min Dong Chinese', 'Mìng-dĕ̤ng-ngṳ̄ / 閩東語');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Chechen', 'Нохчийн');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Cebuano', 'Sinugboanong Binisaya');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Chamorro', 'Chamoru');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Choctaw', 'Choctaw');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Cherokee', 'ᏣᎳᎩ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Cheyenne', 'Tsetsêhestâhese');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Corsican', 'Corsu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Cree', 'Nehiyaw');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Czech', 'Česky');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kashubian', 'Kaszëbsczi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Old Church Slavonic / Old Bulgarian', 'словѣньскъ / slověnĭskŭ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Chuvash', 'Чăваш');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Welsh', 'Cymraeg');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Danish', 'Dansk');
INSERT INTO Language (EnglishName, NativeName)   VALUES('German', 'Deutsch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Dimli', 'Zazaki');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Lower Sorbian', 'Dolnoserbski');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Divehi', 'ދިވެހިބަސް');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Dzongkha', 'ཇོང་ཁ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ewe', 'Ɛʋɛ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Farsi', 'فارسی');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Greek', 'Ελληνικά');
INSERT INTO Language (EnglishName, NativeName)   VALUES('English', 'English');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Esperanto', 'Esperanto');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Spanish', 'Español');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Estonian', 'Eesti');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Basque', 'Euskara');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Extremaduran', 'Estremeñu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Peul', 'Fulfulde');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Finnish', 'Suomi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Võro', 'Võro');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Fijian', 'Na Vosa Vakaviti');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Faroese', 'Føroyskt');
INSERT INTO Language (EnglishName, NativeName)   VALUES('French', 'Français');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Arpitan / Franco-Provençal', 'Arpitan / francoprovençal');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Friulian', 'Furlan');
INSERT INTO Language (EnglishName, NativeName)   VALUES('West Frisian', 'Frysk');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Irish', 'Gaeilge');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Gan Chinese', '贛語');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Scottish Gaelic', 'Gàidhlig');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Gilbertese', 'Taetae ni kiribati');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Galician', 'Galego');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Guarani', "Avañe'ẽ");
INSERT INTO Language (EnglishName, NativeName)   VALUES('Gothic', 'gutisk');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Gujarati', 'ગુજરાતી');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Manx', 'Gaelg');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Hausa', 'هَوُسَ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Hakka Chinese', '客家語/Hak-kâ-ngî');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Hawaiian', 'Hawai`i');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Hebrew', 'עברית');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Hindi', 'हिन्दी');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Hiri Motu', 'Hiri Motu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Croatian', 'Hrvatski');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Haitian', 'Krèyol ayisyen');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Hungarian', 'Magyar');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Armenian', 'Հայերեն');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Herero', 'Otsiherero');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Interlingua', 'Interlingua');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Indonesian', 'Bahasa Indonesia');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Interlingue', 'Interlingue');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Igbo', 'Igbo');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Sichuan Yi', 'ꆇꉙ / 四川彝语');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Inupiak', 'Iñupiak');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ilokano', 'Ilokano');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ido', 'Ido');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Icelandic', 'Íslenska');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Italian', 'Italiano');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Inuktitut', 'ᐃᓄᒃᑎᑐᑦ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Japanese', '日本語');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Lojban', 'Lojban');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Javanese', 'Basa Jawa');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Georgian', 'ქართული');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kongo', 'KiKongo');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kikuyu', 'Gĩkũyũ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kuanyama', 'Kuanyama');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kazakh', 'Қазақша');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Greenlandic', 'Kalaallisut');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Cambodian', 'ភាសាខ្មែរ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kannada', 'ಕನ್ನಡ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Khowar', 'کھوار');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Korean', '한국어');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kanuri', 'Kanuri');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kashmiri', 'कश्मीरी / كشميري');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ripuarian', 'Ripoarisch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kurdish', 'Kurdî / كوردی');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Komi', 'Коми');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Cornish', 'Kernewek');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kirghiz', 'Kırgızca / Кыргызча');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Latin', 'Latina');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ladino / Judeo-Spanish', 'Dzhudezmo / Djudeo-Espanyol');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Lango', 'Leb Lango / Luo');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Luxembourgish', 'Lëtzebuergesch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ganda', 'Luganda');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Limburgian', 'Limburgs');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ligurian', 'Líguru');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Lombard', 'Lumbaart');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Lingala', 'Lingála');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Laotian', 'ລາວ / Pha xa lao');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Lithuanian', 'Lietuvių');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Latvian', 'Latviešu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Banyumasan', 'Basa Banyumasan');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Malagasy', 'Malagasy');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Mandarin', '官話/官话');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Marshallese', 'Kajin Majel / Ebon');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Maori', 'Māori');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Minangkabau', 'Minangkabau');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Macedonian', 'Македонски');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Malayalam', 'മലയാളം');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Mongolian', 'Монгол');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Moldovan', 'Moldovenească');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Marathi', 'मराठी');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Malay', 'Bahasa Melayu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Maltese', 'bil-Malti');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Creek / Muskogee', 'Mvskoke');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Burmese', 'Myanmasa');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Nauruan', 'Dorerin Naoero');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Nahuatl', 'Nahuatl');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Neapolitan', 'Nnapulitano');
INSERT INTO Language (EnglishName, NativeName)   VALUES('North Ndebele', 'Sindebele');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Low German / Low Saxon', 'Plattdüütsch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Dutch Low Saxon', 'Nedersaksisch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Nepali', 'नेपाली');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Newar', 'नेपालभाषा / Newah Bhaye');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ndonga', 'Oshiwambo');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Dutch', 'Nederlands');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Norwegian Nynorsk', 'Norsk (nynorsk)');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Norwegian', 'Norsk (bokmål / riksmål)');
INSERT INTO Language (EnglishName, NativeName)   VALUES('South Ndebele', 'isiNdebele');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Northern Sotho', 'Sesotho sa Leboa / Sepedi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Norman', 'Nouormand / Normaund');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Navajo', 'Diné bizaad');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Chichewa', 'Chi-Chewa');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Occitan', 'Occitan');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Oromo', 'Oromoo');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Oriya', 'ଓଡ଼ିଆ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ossetian / Ossetic', 'Иронау');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Panjabi / Punjabi', 'ਪੰਜਾਬੀ / पंजाबी / پنجابي');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Pangasinan', 'Pangasinan');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kapampangan', 'Kapampangan');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Papiamentu', 'Papiamentu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Pennsylvania German', 'Deitsch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Pali', 'Pāli / पाऴि');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Norfolk', 'Norfuk');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Polish', 'Polski');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Piedmontese', 'Piemontèis');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Pashto', 'پښتو');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Portuguese', 'Português');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Quechua', 'Runa Simi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Raeto Romance', 'Rumantsch');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Romani', 'Romani / रोमानी');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kirundi', 'Kirundi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Romanian', 'Română');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Aromanian', 'Armâneashti');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Russian', 'Русский');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Rwandi', 'Kinyarwandi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Sanskrit', 'संस्कृतम्');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Sardinian', 'Sardu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Sicilian', 'Sicilianu');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Scots', 'Scots');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Sindhi', 'सिनधि');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Northern Sami', 'Davvisámegiella');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Sango', 'Sängö');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Serbo-Croatian', 'Srpskohrvatski / Српскохрватски');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Sinhalese', 'සිංහල');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Simple English', 'Simple English');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Slovak', 'Slovenčina');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Slovenian', 'Slovenščina');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Samoan', 'Gagana Samoa');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Shona', 'chiShona');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Somalia', 'Soomaaliga');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Albanian', 'Shqip');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Serbian', 'Српски');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Swati', 'SiSwati');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Southern Sotho', 'Sesotho');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Sundanese', 'Basa Sunda');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Swedish', 'Svenska');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Swahili', 'Kiswahili');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tamil', 'தமிழ்');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Telugu', 'తెలుగు');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tetum', 'Tetun');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tajik', 'Тоҷикӣ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Thai', 'ไทย / Phasa Thai');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tigrinya', 'ትግርኛ');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Turkmen', 'Туркмен / تركمن');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tagalog', 'Tagalog');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Klingon', 'tlhIngan-Hol');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tswana', 'Setswana');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tonga', 'Lea Faka-Tonga');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tok Pisin', 'Tok Pisin');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Turkish', 'Türkçe');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tsonga', 'Xitsonga');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tatar', 'Tatarça');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tumbuka', 'chiTumbuka');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Twi', 'Twi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Tahitian', 'Reo Mā`ohi');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Udmurt', 'Удмурт кыл');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Uyghur', 'Uyƣurqə / ئۇيغۇرچە');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Ukrainian', 'Українська');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Urdu', 'اردو');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Uzbek', 'Ўзбек');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Venda', 'Tshivenḓa');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Vietnamese', 'Tiếng Việt');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Venetian', 'Vèneto');
INSERT INTO Language (EnglishName, NativeName)   VALUES('West Flemish', 'West-Vlaoms');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Volapük', 'Volapük');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Walloon', 'Walon');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Waray / Samar-Leyte Visayan', 'Winaray / Binisaya Lineyte-Samarnon');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Wolof', 'Wollof');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Kalmyk', 'Хальмг');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Xhosa', 'isiXhosa');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Yiddish', 'ייִדיש');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Yoruba', 'Yorùbá');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Zhuang', 'Cuengh / Tôô / 壮语');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Chinese', '中文');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Classical Chinese', '文言');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Minnan', 'Bân-lâm-gú');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Cantonese', '粵語 / 粤语');
INSERT INTO Language (EnglishName, NativeName)   VALUES('Zulu', 'isiZulu');
